### ISSUE TITLE
Cannot get this working

### ISSUE THREAD

**Issue by iainp999** [simonhq/accu_allergies#4]
Hi there,

I've installed the automation via HACS, but do not see any sensor data.  I can't find any reference to this repo elsewhere, for example in the supervisor section or in the list of repos, so have installed from the only place where I can in the UI.

What am I missing?  Thanks!

**Comment by simonhq** [comment]
Hi Iain,

This is an AppDaemon app, once installed and you have added the details for your postcode etc. as per the instructions to your apps.yaml file in /appdaemon folder you should be able to see the logs of what it is doing in the superviser->appdaemon4 panel.

If you are getting errors in the appdaemon logs, let me know and I will have a look at it.

Simon.

**Comment by iainp999** [comment]
Thanks for your help @simonhq 

One final step - could you help me with the location to place the dependencies please?

i.e. this piece of config

system_packages: []
python_packages:
  - bs4
init_commands: []

I added it to appdaemon.yaml, under the appdaemon section.  Nothing changed at runtime, but I didn't try rebooting and wanted to check that this was the correct place first?

**Comment by iainp999** [comment]
I am seeing the following in the logs, so clearly I have not found the correct place for the config :)

```
2020-08-25 13:06:50.234691 WARNING AppDaemon: Unexpected error loading module: /config/appdaemon/apps/accu_allergies/accu_allergies.py:
2020-08-25 13:06:50.234798 WARNING AppDaemon: ------------------------------------------------------------
2020-08-25 13:06:50.237361 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/appdaemon.py", line 2026, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/usr/lib/python3.8/site-packages/appdaemon/appdaemon.py", line 1809, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/accu_allergies/accu_allergies.py", line 39, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
```

**Comment by iainp999** [comment]
Nevermind, I found it in the UI, when I was looking for a place on the filesystem.

It is at the config tab under superviser->appdaemon - in case any lands here.

**Comment by iainp999** [comment]
Thanks again @simonhq !  Closing.

**Comment by simonhq** [comment]
Great! glad it is working for you!
