### ISSUE TITLE
AccuWeather Allergies not working

### ISSUE THREAD

**Issue by joaopequeno-git** [simonhq/accu_allergies#6]
Hello @simonhq 

The AccuWeather Allergies stop working.
Can you help?

**Comment by simonhq** [comment]
Hi Joaopequeno-git

The accu_weather website has changed, and I need to do some analysis to get this working again, I will try to get this back up soon.

Simon.

**Comment by simonhq** [comment]
I believe that I have resolved this now, please update through HACS and let me know if you have any more issues.

**Comment by joaopequeno-git** [comment]
> 
> 
> I believe that I have resolved this now, please update through HACS and let me know if you have any more issues.

Hello,

I have updated, but still not working, i dont get the sensors created.

**Comment by simonhq** [comment]
Hi joaopequeno-git

Can you let me know what is in your appdaemon log please?

Simon.

**Comment by joaopequeno-git** [comment]
> 
> 
> Hi joaopequeno-git
> 
> Can you let me know what is in your appdaemon log please?
> 
> Simon.

```
2020-10-13 22:41:36.131194 INFO HASS: Connected to Home Assistant 0.116.2
2020-10-13 22:41:37.207404 INFO HASS: Evaluating startup conditions
2020-10-13 22:41:37.333035 INFO HASS: Startup condition met: hass state=RUNNING
2020-10-13 22:41:37.335724 INFO HASS: All startup conditions met
2020-10-13 22:41:37.527268 INFO AppDaemon: Processing restart for HASS
2020-10-13 22:41:37.531014 INFO AppDaemon: Terminating accu_allergies
2020-10-13 22:41:37.540333 INFO AppDaemon: Initializing app accu_allergies using class Get_Accu_Allergies from module accu_allergies
2020-10-13 22:41:37.594985 WARNING accu_allergies: ------------------------------------------------------------
2020-10-13 22:41:37.598481 WARNING accu_allergies: Unexpected error running initialize() for accu_allergies
2020-10-13 22:41:37.603197 WARNING accu_allergies: ------------------------------------------------------------
2020-10-13 22:41:37.613502 WARNING accu_allergies: Traceback (most recent call last):
  File "/usr/lib/python3.8/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'ragweed'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 150, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 290, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/accu_allergies/accu_allergies.py", line 93, in initialize
    self.load_sensors()
  File "/config/appdaemon/apps/accu_allergies/accu_allergies.py", line 188, in load_sensors
    self.get_allergies_rag_info(self.url_txt_xtd[0][2])
  File "/config/appdaemon/apps/accu_allergies/accu_allergies.py", line 246, in get_allergies_rag_info
    html_info = allergies_db[txt]
  File "/usr/lib/python3.8/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
KeyError: b'ragweed'
2020-10-13 22:41:37.619645 WARNING accu_allergies: ------------------------------------------------------------
```

**Comment by simonhq** [comment]
Hey,

Ah, yes I was getting this during my development, it is just a mix up between the old system and the new one, it can be fixed a number of ways, but the 'easiest' is to uninstall the app, restart appdaemon, and then reinstall and that should flush the memory structure so that it isn't trying to load from the old 'save'.

hope this works for you

Simon.

**Comment by joaopequeno-git** [comment]
> 
> 
> Hey,
> 
> Ah, yes I was getting this during my development, it is just a mix up between the old system and the new one, it can be fixed a number of ways, but the 'easiest' is to uninstall the app, restart appdaemon, and then reinstall and that should flush the memory structure so that it isn't trying to load from the old 'save'.
> 
> hope this works for you
> 
> Simon.

Thanks.
Its working!

**Comment by simonhq** [comment]
Great!
